name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  LLM_KEY:
    description: "API key for the LLM."
    required: true
  LLM_MODEL:
    description: "API model name."
    required: true
  LLM_BASE_URL:
    description: "LLM model base url."
    required: true
  output_var:
    description: "Output information to the env"
    required: true
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
